### ISSUE TITLE
Basic API key functionality

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer-v3#146]
**Proposal for V1 API Keys:**

- Create an API endpoint, that allows generating an API key on-demand
- Pass the following fields: name, website, email. Get a key in return.
- Instructions for how to set the key in the header
- Make sure that this header is ignored for caching on Cloudflare

In other words, it's purely about starting to collect API keys, so that we can monitor usage and add limits in the future.

**Future improvements (V2):**

- On Cloudflare, have a different rate limit for API key vs no API key (just if header is set)
- On Indexer, have another layer of rate limiting, if key is valid or not
- Ability to manually bump up the rate limit for known applications
- Ability to keep keys / limits in sync between indexers

The reason for doing key validation on the indexer is that it's easier to build a self-service system, which is a better UX. It also makes the functionality available to other people running it.

**Further improvements (V3):**

- Key checking on Cloudflare, to avoid even reaching Indexer

**Comment by dikkeduif** [comment]
I see three ways we can do this:
1. Code inside the indexer app, and add middleware to each route for checking rate limits
2. A service (ms) outside of the indexer, that we host next to the indexer.
3. Workers or lambda in CloudFlare

2 and 3 are the same idea actually, but with a different implementation

### 1. Code Inside the indexer

Pros:
- Each indexer has the logic built in for doing rate limiting
- We can allow users that want to run their own indexer to turn it on or off with a setting
- We're familiar with the code and we already have redis/databases running for each indexer
- Most simple solution if we have only one indexer with one db

Cons:
- Simplest solution if we have one indexer, but gets complicated with multiple indexers, because keys needs to be synced and there might be delays/issues while syncing these keys
-  Will need to add an event queueing system such as rabbit, so indexers can react to events (key_added, key_removed) and update their respective database
- We need a solution for when we add a completely new indexer. This indexer needs to request all the keys that were previously added. 

### 2. A new service that acts as a proxy, that sits in between the client and indexer

Almost like an API gateway

Pros:
- Decouple API key logic from the actual indexers. Indexers only have relevant business logic.
- This service can be run serverless with autoscaling
- We can easily swap out this service with a different solution, or disable it completely.
- No need to sync keys, this service will have its own database. It only acts as a proxy.

Cons:
- Such as every proxy, it adds latency to a request, but it doesn't necessarily need to be much
- Another service to create and to maintain, needs a pipeline etc
- Single point of failure, need to deploy it over different regions if possible
- Will it have a shared database? If so, the database also becomes a single point of failure, and if its not, we need to sync keys again with events.

### 3. CloudFlare workers or lambda

It's almost the same as number two with some added benefits, and it think it makes sense if we are working towards V3.

Pros:
- Workers are deployed in all regions, single point of failure should be mitigated by this
- CloudFlare has something called Workers KV (key/value storage), where we can keep the keys, no need to sync and it seems it highly scalable and low latency
- I think we can build this with very minimal code

Cons:
- Same as 2, without having to worry about scaling up or syncing keys
- Added costs, but it also reduces some overhead
- Serverless.com tools can be used to deploy and manage the code, but unknown to me, so will need to investigate and play around with this.

### Conclusion

To me 3 feels like the best solution, and it also allows us to explore serverless and workers, which might come in handy for the indexer. It's probably the most robust, without having to do any heavy coding. I would probably try to avoid any solution where we need to sync keys over multiple databases.

Might have missed some pros/cons, interested in hearing what you guys think.

And I think it's still a good idea to contact CloudFlare and maybe see if they have any suggestions on how we can achieve this via workers. There might be some limitations I'm unaware of. The code itself for the workers looks pretty simple.

**Comment by ptrwtts** [comment]
Just to summarize where I landed on this:

Even if long term we want to find a way to use cloudflare rate limiting (workers or otherwise), in the short term, we should just add an API to the indexer that allows creating an API key, so that we can start to track usage.

**Comment by dikkeduif** [comment]
Btw, I found this as well
https://blog.upstash.com/redis-cloudflare-workers

Not sure why I read somewhere redis is not a possibility for workers, but it works just fine. Upstash is also a hosted solution for redis with high availability. Might be interesting to look at this in the future
