### ISSUE TITLE
Simplify response in collections API

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer-v3#85]
Get rid of nesting, and just return the following fields

- id
- name
- image
- description
- tokenCount
- rank
- floorSellValue
- topBuyValue

All information should come from cache.

**Comment by georgeroman** [comment]
@ptrwtts Is it the time to have this simplification for the lite indexer? Now that we have all collections indexed, the collections API is quite slow as it is currently implemented. Having only these fields returned would for sure speed it up. One other concern I have is the sort options for the collections - which are id (very efficient since that's an indexed column) and floor cap (token count * floor sell - which is inefficient since none of these columns are indexed).
